X-RocketTIP: 1.2.3.4
X-RocketSRV: allow=stuff
Received: from [66.228.162.131] by combat.corp.yahoo.com:88 via HTTP; Tue, 17 Mar 2009 22:11:49 UTC
To: Ben Shellack <bs@yahoo.com>\
Subject: Yiv Certified Video Test Message
Content-Type: text/html; charset=us-ascii
MIME-Version: 1.0

<XHTML-VIDEO-EMBED width=400px height=330px params="vid=http%3a%2f%2fvid.host.com%2farchive%2f20090315SpecialReport.flv%3fsenderParam1%3d1%26senderParam2%3d13213&trackingid=12345565456&autoplay=true"/>
