From San Oo Mon Mar 12 13:40:48 2007
X-Apparently-To: buggy_messages@yahoo.com via 68.142.207.151; Mon, 12 Mar 2007 13:40:48 -0700
X-Originating-IP: [68.142.207.151]
Return-Path: <sanwai_work@yahoo.com>
Authentication-Results: mta285.mail.re4.yahoo.com  from=yahoo.com; domainkeys=pass (ok)
Received: from 68.142.207.151  (HELO web32303.mail.mud.yahoo.com) (68.142.207.151)
  by mta285.mail.re4.yahoo.com with SMTP; Mon, 12 Mar 2007 13:40:48 -0700
Received: (qmail 70624 invoked by uid 60001); 12 Mar 2007 20:40:48 -0000
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws;
  s=s1024; d=yahoo.com;
  h=X-YMail-OSG:Received:Date:From:Subject:To:MIME-Version:Content-Type:Content-Transfer-Encoding:Message-ID;
  b=JF2cY+nxGxmSNd1OpEO2IKmXaowmQVmKzAq0fb/jlBE71Z6/L2PKyDLAc+B047Taq8dBwGaje6kipqv6S0wQ246DJUcPtzeN6F2lMwen0G1S2lr148egMKShrJAb7beY3a5+hIc6lQlvt78vKPp33+v2o7+LNdq5t6qG8lrCDZA=;
X-YMail-OSG: KA6it88VM1kbmKMIlH7nmnRLN3duHJZJjlMVnWrsMI5wCm7ySsdhzlY4cROGnfkygRYdgh4fuo2BqsDYYL1GtlgkW8DVy4Sy0nNU09Fc0udn0ZAOOIxWpazXHgbJ9t7S35sPIZabmqXgkhE-
Received: from [207.126.230.225] by web32303.mail.mud.yahoo.com via HTTP; Mon, 12 Mar 2007 13:40:48 PDT
Date: Mon, 12 Mar 2007 13:40:48 -0700 (PDT)
From: San Oo <sanwai_work@yahoo.com>
Subject: Fwd: P1  - DNS resolver issue (TK#1-225483183)
To: buggy_messages@yahoo.com
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="0-1905883516-1173732048=:69597"
Content-Transfer-Encoding: 8bit
Message-ID: <250462.69597.qm@web32303.mail.mud.yahoo.com>
Content-Length: 6731

--0-1905883516-1173732048=:69597
Content-Type: multipart/alternative; boundary="0-1773513318-1173732048=:69597"

--0-1773513318-1173732048=:69597
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: 8bit



Note: forwarded message attached.
--0-1773513318-1173732048=:69597
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: 8bit

<BR><BR>Note: forwarded message attached.
--0-1773513318-1173732048=:69597--
--0-1905883516-1173732048=:69597
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

X-Apparently-To: sanwai_work@yahoo.com via 68.142.207.151; Sun, 11 Mar 2007 16:40:59 -0700
X-Originating-IP: [216.145.54.173]
Authentication-Results: mta486.mail.mud.yahoo.com  from=yahoo-inc.com; domainkeys=fail (bad sig)
Received: from 216.145.54.173  (EHLO mrout3.yahoo.com) (216.145.54.173)
  by mta486.mail.mud.yahoo.com with SMTP; Sun, 11 Mar 2007 16:40:59 -0700
Received: from ilist.yahoo.com (ilist.yahoo.com [216.145.54.177])
	by mrout3.yahoo.com (8.13.6/8.13.6/y.out) with ESMTP id l2BNedNa022872;
	Sun, 11 Mar 2007 16:40:39 -0700 (PDT)
DomainKey-Signature: a=rsa-sha1; s=serpent; d=yahoo-inc.com; c=nofws; q=dns;
	h=received:authentication-results:x-ymail-osg:x-rocketymmf:date:
	from:reply-to:subject:to:cc:mime-version:content-type:
	content-transfer-encoding:message-id:x-loop:errors-to:x-no-archive:x-sequence:
	precedence:list-id;
	b=lj5nVAJvMLLs8IMWhZ1esYu7WdXEVRIFAb323rQgcb/yeKttgpdb/W790iMrPR7L
Received: (from root@localhost)
	by ilist.yahoo.com (8.13.8/8.13.8/ilist) id l2BNectB042023;
	Sun, 11 Mar 2007 16:40:38 -0700 (PDT)
Received: from mrout2.yahoo.com (mrout2.yahoo.com [216.145.54.172])
	by ilist.yahoo.com (8.13.8/8.13.8/ilist) with ESMTP id l2BNeKbY041772;
	Sun, 11 Mar 2007 16:40:21 -0700 (PDT)
Received: from ilist.yahoo.com (ilist.yahoo.com [216.145.54.177])
	by mrout2.yahoo.com (8.13.6/8.13.6/y.out) with ESMTP id l2BNeBrN023211;
	Sun, 11 Mar 2007 16:40:11 -0700 (PDT)
Received: (from root@localhost)
	by ilist.yahoo.com (8.13.8/8.13.8/ilist) id l2BNeB06041688;
	Sun, 11 Mar 2007 16:40:11 -0700 (PDT)
Received: from mrout3.yahoo.com (mrout3.yahoo.com [216.145.54.173])
	by ilist.yahoo.com (8.13.8/8.13.8/ilist) with ESMTP id l2BNe3Qt041620
	for <ymail-all@ilist.yahoo.com>; Sun, 11 Mar 2007 16:40:03 -0700 (PDT)
Received: from mrin1.yahoo.com (mrin1.yahoo.com [216.145.48.32])
	by mrout3.yahoo.com (8.13.6/8.13.6/y.out) with ESMTP id l2BNdufl022473
	for <ymail-all@ilist.yahoo.com>; Sun, 11 Mar 2007 16:39:58 -0700 (PDT)
Received: from web57013.mail.re3.yahoo.com (web57013.mail.re3.yahoo.com [66.196.97.117])
	by mrin1.yahoo.com (8.13.8/8.13.8/y.in) with SMTP id l2BNdtZl008693
	for <ymail-all@yahoo-inc.com>; Sun, 11 Mar 2007 16:39:55 -0700 (PDT)
Authentication-Results: mrin1.yahoo.com From=krish@yahoo-inc.com; domainkeys=pass (testing)
Received: (qmail 72635 invoked by uid 60001); 11 Mar 2007 23:39:55 -0000
X-YMail-OSG: Oswdyr0VM1lfYOl20bAcXHCyxUkEExQgA3acurpMufFJbvYxKUGLabokc3JeZhPxJm93Td3V0WeSv4qoDFP3cRWkmDUSAwDbSmbQxSEK3tn7tOLYu12vS8FgbVQR._p4FJOxVhdMX6D71.8-
Received: from [216.145.54.7] by web57013.mail.re3.yahoo.com via HTTP; Sun, 11 Mar 2007 16:39:55 PDT
Date: Sun, 11 Mar 2007 16:39:55 -0700 (PDT)
From: Krish <krish@yahoo-inc.com>
Reply-To: krish@yahoo-inc.com
Subject: Fwd: P1  - DNS resolver issue (TK#1-225483183)
To: ymail-all@yahoo-inc.com
Cc: mchan@yahoo-inc.com
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="0-237247821-1173656395=:55745"
Content-Transfer-Encoding: 8bit
X-Loop: ymail-all@yahoo-inc.com
Errors-to: ymail-all-owner@yahoo-inc.com
X-no-archive: yes
X-Loop: ymail-devel@yahoo-inc.com
X-Sequence: 4978
Errors-to: ymail-devel-owner@yahoo-inc.com
Precedence: bulk
X-no-archive: yes
List-Id: <ymail-devel.yahoo-inc.com>
Content-Length: 1346

--0-237247821-1173656395=:55745
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: 8bit
Content-Id: 
Content-Disposition: inline

FYI: 

Note: forwarded message attached.



--0-237247821-1173656395=:55745
Content-Type: message/rfc822

X-Apparently-To: krish_yhoo-inc@yahoo.com via 66.196.97.105; Sun, 11 Mar 2007 16:14:54 -0700
X-Originating-IP: [216.145.54.173]
Authentication-Results: mta531.mail.mud.yahoo.com  from=yahoo-inc.com; domainkeys=pass (ok)
Received: from 216.145.54.173  (EHLO mrout3.yahoo.com) (216.145.54.173)
  by mta531.mail.mud.yahoo.com with SMTP; Sun, 11 Mar 2007 16:14:52 -0700
Received: from ilist.yahoo.com (ilist.yahoo.com [216.145.54.177])
	by mrout3.yahoo.com (8.13.6/8.13.6/y.out) with ESMTP id l2BNEgsr014025;
	Sun, 11 Mar 2007 16:14:42 -0700 (PDT)
DomainKey-Signature: a=rsa-sha1; s=serpent; d=yahoo-inc.com; c=nofws; q=dns;
	h=received:date:message-id:x-ems-type:x-ems-priority:subject:to:
	from:reply-to:x-loop:x-sequence:errors-to:precedence:
	x-no-archive:list-id;
	b=s+qWqktGx3mNavqLcjAgpokKpDynp3mAydEM06VrpOp2j/oqUgQDbII6JJxPqZIP
Received: (from root@localhost)
	by ilist.yahoo.com (8.13.8/8.13.8/ilist) id l2BNEf4e025925;
	Sun, 11 Mar 2007 16:14:41 -0700 (PDT)
Received: from mrout2.yahoo.com (mrout2.yahoo.com [216.145.54.172])
	by ilist.yahoo.com (8.13.8/8.13.8/ilist) with ESMTP id l2BNEXPx025886
	for <ymail-oncall@ilist.yahoo.com>; Sun, 11 Mar 2007 16:14:33 -0700 (PDT)
Received: from mrin1-b.corp.dcn.yahoo.com (mrin1-b.corp.dcn.yahoo.com [216.109.112.71])
	by mrout2.yahoo.com (8.13.6/8.13.6/y.out) with ESMTP id l2BNE63J014592;
	Sun, 11 Mar 2007 16:14:06 -0700 (PDT)
Received: from ems1.ops.re3.yahoo.com (ems1.ops.re3.yahoo.com [68.142.238.15])
	by mrin1-b.corp.dcn.yahoo.com (8.13.8/8.13.6/y.in) with ESMTP id l2BNDwbP032648;
	Sun, 11 Mar 2007 16:13:59 -0700 (PDT)
Received: (from nobody@localhost)
	by ems1.ops.re3.yahoo.com (8.13.6/8.13.6) id l2BNDnW1051278;
	Sun, 11 Mar 2007 16:13:49 -0700 (PDT)
	(envelope-from nobody)
Date: Sun, 11 Mar 2007 16:13:49 -0700 (PDT)
X-EMS-TYPE: Internal Event Notify
X-EMS-PRIORITY: 1
Subject: P1  - DNS resolver issue (TK#1-225483183)
To: nobody@yahoo-inc.com
From: Yahoo! NOC <ynoc-request@yahoo-inc.com>
Reply-To: ymail-oncall@yahoo-inc.com, Yahoo! NOC <ynoc-request@yahoo-inc.com>
X-Loop: ymail-oncall@yahoo-inc.com
X-Sequence: 589971
Errors-to: ymail-oncall-owner@yahoo-inc.com
Precedence: bulk
X-no-archive: yes
List-Id: <ymail-oncall.yahoo-inc.com>

Status: Stable -Srv. Impact: 6 Hrs 15 Mins 

Description:Mail farms are no longer experiencing issues in mud or re2. Y! Sports, Rogers and Verizon partner farms and ATT Pops have not reported any more problems related to this event. The issue was related to traffic overload on DNS resolvers possibly due to excess spam. DNS team, Tier 2 and Ymail Oncall are still investigating root cause. 

Evnt Dur: 6 Hrs 24 Mins  -YNOC,x5555

--0-237247821-1173656395=:55745--

--0-1905883516-1173732048=:69597--
