Date: Wed, 23 Nov 2016 22:13:21 +0000 (UTC)
From: Anirudh Acharya <anirudh.ydogfood@yahoo.com>
Reply-To: Anirudh Acharya <anirudh.ydogfood@yahoo.com>
To: Anirudh Acharya <anirudh.ydogfood@yahoo.com>
Subject: GSB Msg with TextDecoration And border Ttag
MIME-Version: 1.0
Content-Type: multipart/alternative;
    boundary="----=_Part_827183_2018524773.1479939201759"
References: <2116891728.827184.1479939201760.ref@mail.yahoo.com>
Content-Length: 611

------=_Part_827183_2018524773.1479939201759
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Hi, this is a test message. Reply to this with text-decoration-[line|style|color] and border-[top|bottom]-[left|right]-radius.
------=_Part_827183_2018524773.1479939201759
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html><head></head><body><div style="text-decoration-line:none;border-top-left-radius:2px;border-top-right-radius:2px;border-bottom-right-radius:2px;border-bottom-left-radius:2px;">text</div></body></html>
------=_Part_827183_2018524773.1479939201759--